name: Kubectl CI

on:
  push:
  pull_request:

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: RUN Lint
        run: echo "lint passed"

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: RUN Build
        run: echo "build passed"

  test:
    needs: build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Kubectl

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: /Kubectl/pnpm-lock.yaml

      - name: install dependency
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm run test

      - name: build application
        run: echo "application build passed"

  docker:
    needs:
      - lint
      - test
      - build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build docker image
        run: echo "Docker build passed"
